
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package org.example.ParserLexer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 55;
  public static final int DIVIDE = 49;
  public static final int STRING_LITERAL = 25;
  public static final int FUNCTION = 16;
  public static final int CHAR_LITERAL = 26;
  public static final int IMPRIMIR = 14;
  public static final int CHAR_T = 31;
  public static final int DIFERENTE = 40;
  public static final int CASE = 9;
  public static final int RESTA = 47;
  public static final int MATRX = 19;
  public static final int BRACEIZQ = 65;
  public static final int FOR = 7;
  public static final int PARAM = 21;
  public static final int MENORIGUAL = 38;
  public static final int MULTIPLICA = 48;
  public static final int IN = 22;
  public static final int BOOL = 33;
  public static final int INCREMENTO = 52;
  public static final int SUMA = 46;
  public static final int ASIGNA = 45;
  public static final int MAIN = 17;
  public static final int IF = 2;
  public static final int MAYORIGUAL = 39;
  public static final int EOF = 0;
  public static final int END_BLOC = 63;
  public static final int RETURN = 12;
  public static final int ARRX = 18;
  public static final int TRUE = 35;
  public static final int DECREMENTO = 53;
  public static final int error = 1;
  public static final int INTEGER_T = 27;
  public static final int COMA = 54;
  public static final int INIT_BLOC = 62;
  public static final int PIPE = 58;
  public static final int MODULO = 50;
  public static final int NEGACION = 43;
  public static final int MENOR = 36;
  public static final int EZH_DE = 57;
  public static final int GLOBAL = 15;
  public static final int BREAK = 10;
  public static final int VOID = 24;
  public static final int BRACEDER = 64;
  public static final int SWITCH = 8;
  public static final int ESH_IZ = 56;
  public static final int MAYOR = 37;
  public static final int POTENCIA = 51;
  public static final int ELSE = 4;
  public static final int PUNTO = 23;
  public static final int WHILE = 6;
  public static final int DEFAULT = 11;
  public static final int CONJUNCION = 41;
  public static final int LEER = 13;
  public static final int FLOAT_T = 30;
  public static final int FINLINEA = 59;
  public static final int COMPARACION = 44;
  public static final int END_COMMENT = 61;
  public static final int DISYUNCION = 42;
  public static final int FLOAT_LITERAL = 66;
  public static final int INIT_COMMENT = 60;
  public static final int FALSE = 34;
  public static final int STRUCT = 20;
  public static final int STRING_T = 32;
  public static final int ELIF = 3;
  public static final int DO = 5;
  public static final int INTEGER_LITERAL = 28;
  public static final int IDENTIFIER = 29;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "ELIF",
  "ELSE",
  "DO",
  "WHILE",
  "FOR",
  "SWITCH",
  "CASE",
  "BREAK",
  "DEFAULT",
  "RETURN",
  "LEER",
  "IMPRIMIR",
  "GLOBAL",
  "FUNCTION",
  "MAIN",
  "ARRX",
  "MATRX",
  "STRUCT",
  "PARAM",
  "IN",
  "PUNTO",
  "VOID",
  "STRING_LITERAL",
  "CHAR_LITERAL",
  "INTEGER_T",
  "INTEGER_LITERAL",
  "IDENTIFIER",
  "FLOAT_T",
  "CHAR_T",
  "STRING_T",
  "BOOL",
  "FALSE",
  "TRUE",
  "MENOR",
  "MAYOR",
  "MENORIGUAL",
  "MAYORIGUAL",
  "DIFERENTE",
  "CONJUNCION",
  "DISYUNCION",
  "NEGACION",
  "COMPARACION",
  "ASIGNA",
  "SUMA",
  "RESTA",
  "MULTIPLICA",
  "DIVIDE",
  "MODULO",
  "POTENCIA",
  "INCREMENTO",
  "DECREMENTO",
  "COMA",
  "DOSPUNTOS",
  "ESH_IZ",
  "EZH_DE",
  "PIPE",
  "FINLINEA",
  "INIT_COMMENT",
  "END_COMMENT",
  "INIT_BLOC",
  "END_BLOC",
  "BRACEDER",
  "BRACEIZQ",
  "FLOAT_LITERAL"
  };
}

